name: pokedex_flutter
description: "A Pokedex App in Flutter"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  flutter_modular: ^6.3.4
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  easy_localization: ^3.0.7+1
  flutter_svg: ^2.0.17
  brasil_fields: ^1.15.0
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  timezone: ^0.10.0
  mask_text_input_formatter: ^2.9.0
  fluttertoast: ^8.2.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  fl_chart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.5
  mobx_codegen: ^2.1.1

flutter:
  assets:
    - .env
    - assets/images/pokeball.svg

  uses-material-design: true
